name: Promote Image

on:
  workflow_dispatch:
    inputs:
      ci_image_name:
        required: true
      team_image_name:
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🚀 Promote Azure Image
        uses: your-org/ci-infra/.github/actions/promote-image@main
        with:
          ci_image_name: ${{ github.event.inputs.ci_image_name }}
          team_image_name: ${{ github.event.inputs.team_image_name }}
        secrets:
          CI_CLIENT_ID: ${{ secrets.CI_CLIENT_ID }}
          CI_CLIENT_SECRET: ${{ secrets.CI_CLIENT_SECRET }}
          CI_TENANT_ID: ${{ secrets.CI_TENANT_ID }}
          CI_SUBSCRIPTION_ID: ${{ secrets.CI_SUBSCRIPTION_ID }}
          CI_RESOURCE_GROUP: ${{ secrets.CI_RESOURCE_GROUP }}
          TEAM_CLIENT_ID: ${{ secrets.TEAM_CLIENT_ID }}
          TEAM_CLIENT_SECRET: ${{ secrets.TEAM_CLIENT_SECRET }}
          TEAM_TENANT_ID: ${{ secrets.TEAM_TENANT_ID }}
          TEAM_SUBSCRIPTION_ID: ${{ secrets.TEAM_SUBSCRIPTION_ID }}
          TEAM_RESOURCE_GROUP: ${{ secrets.TEAM_RESOURCE_GROUP }}
